### ISSUE TITLE
Write introductory text

### ISSUE THREAD

**Issue by lauren-walker** [lauren-walker/TopicViz#23]
- This will display when the visualization first loads. Keep it short
- Include link to this Github repo with visualization code and possibly mention Codefest

**Comment by davharris** [comment]
I can help with some of this if you'd like.  I'm really excited to see that this is getting some more attention.  Let me know if there's anything else I can help with, too.

**Comment by lauren-walker** [comment]
Hi David! You can contribute to the project any way you would like. It would be great to get a little bit of text from you describing some of the work you did on determining the x,y coords of each of the nodes in the visualization. 

Our Associate Director of Communications at NCEAS is planning on showing this off at the ESA conference this August so I created a 1.0.0 milestone in GitHub to organize some of the features we want for its debut there. We will be including a list of contributors which includes yourself and others from Codefest last year.

**Comment by davharris** [comment]
Great.  Here's a brief informal summary of what I did.  I'd be happy to expand or clarify or revise anything that isn't clear or formal enough :-)

Each document has a 87 of scores based on the 100-dimensional LDA model.  I tried a few ways of calculating the "distance" between these documents in 87-dimensional space and found that the Hellinger distance (which is like Euclidean distance on the square roots of the original scores) worked well.

I then used t-distributed stochastic neighbor embedding (t-SNE, pronounced tee-snee) to turn those distances into locations in 2D space.  t-SNE pulls each document together with its nearest neighbors in 2D space, but it doesn't particularly try to push *dissimilar* documents apart.  As a result, it tends to make very nice clusters of similar documents, but it doesn't have much long-range structure (so, unlike PCA embeddings, for example, the axes themselves don't mean much).

I used the `tsne` R package by Justin Donaldson <jdonaldson@gmail.com> for the embedding.  The original t-sne method is described [here](https://lvdmaaten.github.io/publications/papers/JMLR_2008.pdf).

Again, please let me know if any of this needs clarifying/polishing/etc.  Thanks again for pushing ahead with this.  I'm excited to see the final result.
