### ISSUE TITLE
pre-existing "TopicViz" software

### ISSUE THREAD

**Issue by davharris** [lauren-walker/TopicViz#26]
We might want to consider changing the name.

http://arxiv.org/abs/1110.6200

**Comment by jmaccuish** [comment]
I second this (m)(n)otion. 

Cheers, 
John 

----- Original Message -----

**Comment by lauren-walker** [comment]
Hmm, I'm not sure the problems this could cause and seems likely to happen with a number of given names.

**Comment by jmaccuish** [comment]
Ah, best not to then. 
Best, 
John 

----- Original Message -----
